name: 'lab04-actions'
on: [push, pull_request]
env:
  CMAKE_VERSION: 3.21.1
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ubuntu-latest
  


    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Test_1
        working-directory: /formatter_lib
        shell: bash
        run: |
          VERSION=`cmake --version`
          echo $VERSION
