name: 'lab05-actions'

on:
   push:
     branches:
       - lab05_master
      
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:      
      - name: Git clone
        uses: actions/checkout@v1 
        
      - name: Git checkout
        run : git checkout lab05_master
        
      - name: Git pull
        run : git pull origin lab05_master
    
      - name: Test
        shell: bash
        run: |
          cmake -H. -B_build -DBUILD_TESTS=O
          cmake --build _build
          cmake --build _build --target test
          _build/check
          cmake --build _build --target test -- ARGS=--verbose
      - name: Display coverage
        uses: ewjoachim/coverage-comment-action@v1
        with:

          # Name of the json file containing badge informations stored in the repo wiki.
          BADGE_FILENAME: coverage-comment-badge.json

          # If the coverage percentage is above or equal to this value, the badge will be green.
          MINIMUM_GREEN: 100

          # Same with orange. Below is red.
          MINIMUM_ORANGE: 70

          # [Advanced] Specify a different template for the comments that will be written on the PR.
          COMMENT_TEMPLATE: ""

          # [Advanced] Additional args to pass to diff cover (one per line)
          DIFF_COVER_ARGS: ""
