name: 'lab05-actions'

on:
   push:
     branches:
       - lab05_master
      
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:      
      - name: Git clone
        uses: actions/checkout@v1 
        
      - name: Git checkout
        run : git checkout lab05_master
        
      - name: Git pull
        run : git pull origin lab05_master
    

